[package]
name = "mystic-server"
version = "0.1.0"
authors = ["Stephen Karger"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
env_logger = "0.6"
handlebars = "2.0.0-beta.2"
listenfd = "0.3"
log = "0.4"
serde_json = "1.0"
