[package]
name = "graphql"
version = "0.1.0"
authors = ["Stephen Karger <stephen.karger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
juniper = "0.13"