[package]
name = "db"
version = "0.1.0"
authors = ["Stephen Karger"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
dotenv = "0.14.1"
handlebars = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
